version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: ./common_images_python/Dockerfile.python
    mem_limit: 4g
    mem_reservation: 2g
    ports:
      - "50051:50051"
    volumes:
      - ./server_grpc:/app/server_grpc  # Монтируем server_grpc в контейнер
      - ./server_grpc/hf_cache:/root/.cache/huggingface/hub
    healthcheck:
      test: ["CMD", "python3", "-c", "import grpc; channel = grpc.insecure_channel('localhost:50051'); channel.subscribe(lambda _: True, try_to_connect=True)"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - app_network


  cursedwords_bot:
    image: cwbot:${TARGET_IMAGES_VERSION:-1.0}
    environment:
      - GRPC_SERVER_ADDRESS=grpc_server:50051 
      - command_line_arguments=-token 7229787403:AAH0DVCx0wUQ-G9lkXYoIllHL0DhmdawEZo
    depends_on:
      - grpc_server
    networks:
      - app_network  # Используем ту же сеть

# Явно определяем сеть
networks:
  app_network:
    driver: bridge